version: '3.9'
services:
  app:
    container_name: miapp
    networks:
      - miapp-db
    ports:
      - 3000:3000
    build:
      context: ../
      dockerfile: Dockerfile.dev
      target: dev
    links:
      - "mongodb"
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules 
    command: ["dumb-init", "yarn", "dev"]
  mongodb:
    container_name: mongo-db
    networks:
      - miapp-db
    volumes:
      - mongo-volume:/data/db
    ports:
      - 27017:27017
    image: mongo:7.0.7-rc2-jammy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nico
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    container_name: mongo-express
    networks:
      - miapp-db
    ports:
      - 8081:8081
    image: mongo-express:1.0.2-20-alpine3.19
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mongo-db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=nico
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
  postgres:
    container_name: postgres-db
    networks:
      - postgres-network
    volumes:
      - postgres-volumes:/var/lib/postgresql/data
    ports:
      - 5432:5432
    image: postgres:16.2
    environment:
      - POSTGRES_USERNAME=nicos
      - POSTGRES_PASSWORD=password
  pgAdmin:
    container_name: postgres-panel
    networks:
      - postgres-network
    volumes:
      - pgAdmin-volume:/var/lib/pgadmin
    ports:
      - 8080:80
    image: dpage/pgadmin4:8.4
    environment:
      - PGADMIN_DEFAULT_EMAIL=correo@gmil.com
      - PGADMIN_DEFAULT_PASSWORD=password

networks:
  miapp-db:
   driver: bridge
  postgres-network:
   driver: bridge

volumes:
  mongo-volume:
   external: true
  postgres-volumes:
   external: true
  pgAdmin-volume:
   external: true
